[theme]
base = "light"
primaryColor = "#E41C23"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAF8F4"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
