[theme]
base = "dark"
primaryColor = "#E41C23"
backgroundColor = "#0F0F0E"
secondaryBackgroundColor = "#181816"
textColor = "#EFE9DE"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
